app/src/main/java/com/framgia/fdms/data/model/MeetingRoom.java
app/src/main/java/com/framgia/fdms/data/source/MeetingRoomDataSource.java
app/src/main/java/com/framgia/fdms/data/source/MeetingRoomRepository.java
app/src/main/java/com/framgia/fdms/data/source/api/service/FDMSApi.java
app/src/main/java/com/framgia/fdms/data/source/remote/MeetingRoomRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/meetingroom/listmeetingroom/ListMeetingRoomContract.java
app/src/main/java/com/framgia/fdms/screen/meetingroom/listmeetingroom/ListMeetingRoomFragment.java
app/src/main/java/com/framgia/fdms/screen/meetingroom/listmeetingroom/ListMeetingRoomPresenter.java
app/src/main/java/com/framgia/fdms/screen/meetingroom/listmeetingroom/ListMeetingRoomViewModel.java
app/src/main/java/com/framgia/fdms/utils/Constant.java
app/src/main/res/layout/fragment_list_meeting_room.xml

Task: Call API Get List Meetings Room
Link redmine: https://dev.framgia.com/redmine/issues/135570

[Sprint 12] Feature call API get list meeting room

---

app/src/main/java/com/framgia/fdms/screen/device/DeviceViewModel.java
app/src/main/java/com/framgia/fdms/screen/main/MainActivity.java
app/src/main/java/com/framgia/fdms/screen/main/MainContract.java
app/src/main/java/com/framgia/fdms/screen/main/MainPresenter.java
app/src/main/java/com/framgia/fdms/screen/main/MainViewModel.java
app/src/main/java/com/framgia/fdms/screen/producer/marker/MarkerFragment.java
app/src/main/java/com/framgia/fdms/utils/binding/BindingUtils.java
app/src/main/res/layout/activity_newmain.xml
app/src/main/res/layout/nav_header_main.xml
app/src/main/res/menu/menu_drawer.xml

Link redmine: https://dev.framgia.com/redmine/issues/135637

[Sprint 12] Home screen - Custom UI Again 2

---

app/src/main/java/com/framgia/fdms/data/model/Producer.java
app/src/main/java/com/framgia/fdms/data/source/VendorDataSource.java
app/src/main/java/com/framgia/fdms/data/source/VendorRepository.java
app/src/main/java/com/framgia/fdms/data/source/api/service/FDMSApi.java
app/src/main/java/com/framgia/fdms/data/source/remote/VendorRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/producer/vendor/VendorContract.java
app/src/main/java/com/framgia/fdms/screen/producer/vendor/VendorFragment.java
app/src/main/java/com/framgia/fdms/screen/producer/vendor/VendorPresenter.java
app/src/main/java/com/framgia/fdms/screen/producer/vendor/VendorViewModel.java
app/src/main/res/layout/item_vendor.xml

Redmine : https://dev.framgia.com/redmine/issues/135596

[Sprint 12] Tab Device - Call API Get List Vendor

---

app/src/main/java/com/framgia/fdms/data/source/UserDataSource.java
app/src/main/java/com/framgia/fdms/data/source/UserRepository.java
app/src/main/java/com/framgia/fdms/data/source/local/UserLocalDataSource.java
app/src/main/java/com/framgia/fdms/screen/main/MainContract.java
app/src/main/java/com/framgia/fdms/screen/main/MainPresenter.java
app/src/main/java/com/framgia/fdms/screen/main/MainViewModel.java
app/src/main/java/com/framgia/fdms/utils/Constant.java
app/src/main/java/com/framgia/fdms/utils/binding/BindingUtils.java
app/src/main/res/layout/activity_newmain.xml

Link Redmine: https://dev.framgia.com/redmine/issues/135638

[Task #135638][Sprint 12] Home screen - Reslove Logic When Edit UI

---

app/src/main/java/com/framgia/fdms/data/source/VendorDataSource.java
app/src/main/java/com/framgia/fdms/data/source/VendorRepository.java
app/src/main/java/com/framgia/fdms/data/source/api/error/BaseException.java
app/src/main/java/com/framgia/fdms/data/source/api/service/FDMSApi.java
app/src/main/java/com/framgia/fdms/data/source/remote/VendorRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/producer/vendor/VendorContract.java
app/src/main/java/com/framgia/fdms/screen/producer/vendor/VendorPresenter.java
app/src/main/java/com/framgia/fdms/screen/producer/vendor/VendorViewModel.java

Redmine: https://dev.framgia.com/redmine/issues/136572

[Sprint 12] Tab Device - Call API delete vendor

---

app/src/main/java/com/framgia/fdms/screen/meetingroom/detailmeetingroom/DetailMeetingRoomActivity.java
app/src/main/java/com/framgia/fdms/screen/meetingroom/detailmeetingroom/DetailMeetingRoomContract.java
app/src/main/java/com/framgia/fdms/screen/meetingroom/detailmeetingroom/DetailMeetingRoomPresenter.java
app/src/main/java/com/framgia/fdms/screen/meetingroom/detailmeetingroom/DetailMeetingRoomViewModel.java
app/src/main/java/com/framgia/fdms/screen/meetingroom/detailmeetingroom/ListDeviceAdapter.java
app/src/main/java/com/framgia/fdms/screen/meetingroom/listmeetingroom/ListMeetingRoomFragment.java
app/src/main/java/com/framgia/fdms/screen/meetingroom/listmeetingroom/ListMeetingRoomViewModel.java
app/src/main/java/com/framgia/fdms/utils/Constant.java
app/src/main/res/layout/activity_detail_meeting_room.xml

Task: Feature call API detail meeting room
Link redmine: https://dev.framgia.com/redmine/issues/135570

[Sprint 12] Feature call API detail meeting room

---

app/src/main/java/com/framgia/fdms/data/source/VendorDataSource.java
app/src/main/java/com/framgia/fdms/data/source/VendorRepository.java
app/src/main/java/com/framgia/fdms/data/source/api/service/FDMSApi.java
app/src/main/java/com/framgia/fdms/data/source/remote/VendorRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/producer/ProducerDialog.java
app/src/main/java/com/framgia/fdms/screen/producer/vendor/VendorContract.java
app/src/main/java/com/framgia/fdms/screen/producer/vendor/VendorPresenter.java
app/src/main/java/com/framgia/fdms/screen/producer/vendor/VendorViewModel.java

Redmine: https://dev.framgia.com/redmine/issues/136573

[Sprint 12] Tab Device - Call API edit vendor

---

app/src/main/java/com/framgia/fdms/data/source/api/error/BaseException.java
app/src/main/java/com/framgia/fdms/data/source/api/middleware/RxErrorHandlingCallAdapterFactory.java
app/src/main/java/com/framgia/fdms/data/source/remote/DeviceRemoteDataSource.java

Redmine: https://dev.framgia.com/redmine/issues/136844

[Sprint 12] Update message when no internet connection

---

app/src/main/java/com/framgia/fdms/data/source/VendorDataSource.java
app/src/main/java/com/framgia/fdms/data/source/VendorRepository.java
app/src/main/java/com/framgia/fdms/data/source/api/service/FDMSApi.java
app/src/main/java/com/framgia/fdms/data/source/remote/VendorRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/producer/vendor/VendorContract.java
app/src/main/java/com/framgia/fdms/screen/producer/vendor/VendorPresenter.java
app/src/main/java/com/framgia/fdms/screen/producer/vendor/VendorViewModel.java
app/src/main/res/layout/item_vendor.xml

Redmine: https://dev.framgia.com/redmine/issues/135598

[Sprint 12] Tab Device - Call API Get List Maker

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/framgia/fdms/screen/deviceselection/DeviceSelectionActivity.java
app/src/main/java/com/framgia/fdms/screen/deviceselection/DeviceSelectionAdapter.java
app/src/main/java/com/framgia/fdms/screen/deviceselection/DeviceSelectionContract.java
app/src/main/java/com/framgia/fdms/screen/deviceselection/DeviceSelectionPresenter.java
app/src/main/java/com/framgia/fdms/screen/deviceselection/DeviceSelectionViewModel.java
app/src/main/java/com/framgia/fdms/utils/Constant.java
app/src/main/res/layout/activity_device_selection.xml
app/src/main/res/layout/item_device_selection.xml

Link Redmine: https://dev.framgia.com/redmine/issues/135588

[Task #135588][Sprint 12] Assignment screen - Custom UI again(focus add new device)

---

app/src/main/java/com/framgia/fdms/data/model/AssignmentItemRequest.java
app/src/main/java/com/framgia/fdms/data/model/AssignmentRequest.java
app/src/main/java/com/framgia/fdms/data/source/api/service/FDMSApi.java
app/src/main/java/com/framgia/fdms/screen/assignment/AssignmentAdapter.java
app/src/main/java/com/framgia/fdms/utils/Constant.java

Link redmine:
- https://dev.framgia.com/redmine/issues/135589

[Task #135589][Sprint 12] Assignment screen - Call API Post Assignment

---

app/src/main/java/com/framgia/fdms/data/source/api/service/FDMSApi.java
app/src/main/java/com/framgia/fdms/data/source/remote/VendorRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/producer/vendor/VendorAdapter.java
app/src/main/java/com/framgia/fdms/screen/producer/vendor/VendorContract.java
app/src/main/java/com/framgia/fdms/screen/producer/vendor/VendorPresenter.java
app/src/main/java/com/framgia/fdms/screen/producer/vendor/VendorViewModel.java
app/src/main/java/com/framgia/fdms/utils/binding/BindingUtils.java
app/src/main/res/layout/fragment_vendor.xml

Redmine: https://dev.framgia.com/redmine/issues/136981

[Sprint 12] Tab Device - Call API create marker

---

app/src/main/java/com/framgia/fdms/data/source/api/service/FDMSApi.java
app/src/main/java/com/framgia/fdms/data/source/remote/MarkerRemoteDataSource.java
app/src/main/java/com/framgia/fdms/data/source/remote/VendorRemoteDataSource.java
app/src/main/java/com/framgia/fdms/utils/Utils.java
app/src/main/res/layout/fragment_vendor.xml

Redmine 
- https://dev.framgia.com/redmine/issues/136982
- https://dev.framgia.com/redmine/issues/136983

[Sprint 12] Tab Device - Call API delete marker, Update marker

---

app/src/main/java/com/framgia/fdms/screen/meetingroom/detailmeetingroom/DetailMeetingRoomActivity.java
app/src/main/java/com/framgia/fdms/screen/meetingroom/detailmeetingroom/DetailMeetingRoomViewModel.java
app/src/main/java/com/framgia/fdms/screen/meetingroom/listmeetingroom/ListMeetingRoomViewModel.java
app/src/main/java/com/framgia/fdms/utils/Constant.java
app/src/main/res/drawable/ic_arrow_back_white_24dp.xml
app/src/main/res/layout/activity_detail_meeting_room.xml
app/src/main/res/layout/fragment_list_meeting_room.xml
app/src/main/res/layout/item_list_device_room_detail.xml
app/src/main/res/values/strings.xml

Feature fix UI meeting room detail  https://dev.framgia.com/redmine/issues/135582
Call API Get Meeting Room by Meeting Room Name  https://dev.framgia.com/redmine/issues/135578

Feature fix UI meeting room detail + Search Meeting room by Room Name

---

app/src/main/java/com/framgia/fdms/data/model/MeetingRoom.java
app/src/main/java/com/framgia/fdms/screen/meetingroom/listmeetingroom/ListMeetingRoomContract.java
app/src/main/java/com/framgia/fdms/screen/meetingroom/listmeetingroom/ListMeetingRoomFragment.java
app/src/main/java/com/framgia/fdms/screen/meetingroom/listmeetingroom/ListMeetingRoomPresenter.java
app/src/main/java/com/framgia/fdms/screen/meetingroom/listmeetingroom/ListMeetingRoomViewModel.java
app/src/main/java/com/framgia/fdms/screen/meetingroom/listmeetingroom/MeetingRoomDialog.java
app/src/main/java/com/framgia/fdms/screen/meetingroom/listmeetingroom/MeetingRoomDialogContract.java
app/src/main/java/com/framgia/fdms/screen/meetingroom/listmeetingroom/MeetingRoomFunctionContract.java
app/src/main/java/com/framgia/fdms/utils/Constant.java
app/src/main/res/layout/dialog_confirm_meeting_room.xml

Task: Call API Create Meeting Room
Link redmine: https://dev.framgia.com/redmine/issues/135651
Task: Call API Edit Meeting Room
Link redmine: https://dev.framgia.com/redmine/issues/135574
Task: Call API Delete Meeting Room
Link redmine: https://dev.framgia.com/redmine/issues/135576

[Sprint 12] Feature create, edit, delete meeting room

---

app/src/main/java/com/framgia/fdms/data/source/api/service/FDMSApi.java
app/src/main/java/com/framgia/fdms/screen/device/listdevice/ListDeviceViewModel.java
app/src/main/java/com/framgia/fdms/utils/binding/BindingUtils.java
app/src/main/res/layout/activity_newmain.xml
app/src/main/res/layout/filter_device.xml
app/src/main/res/layout/fragment_list_device.xml
app/src/main/res/values/strings.xml

Redmine: https://dev.framgia.com/redmine/issues/135641

 [Sprint 12] Manager Devices screen 

---

app/src/main/java/com/framgia/fdms/data/source/api/service/FDMSApi.java
app/src/main/java/com/framgia/fdms/data/source/remote/CategoryRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/assignment/AssignmentContract.java
app/src/main/java/com/framgia/fdms/screen/assignment/AssignmentPresenter.java
app/src/main/java/com/framgia/fdms/screen/assignment/AssignmentViewModel.java
app/src/main/java/com/framgia/fdms/screen/deviceselection/DeviceSelectionActivity.java
app/src/main/java/com/framgia/fdms/utils/Constant.java
app/src/main/java/com/framgia/fdms/utils/binding/BindingUtils.java
app/src/main/res/layout/activity_assignment.xml
app/src/main/res/values/strings.xml

Link redmine:
https://dev.framgia.com/redmine/issues/135590

[Task #135590][Sprint 12] Assignment screen - Reslove Logic when Custom UI again

---

app/src/main/java/com/framgia/fdms/screen/assignment/AssignmentAdapter.java
app/src/main/java/com/framgia/fdms/screen/request/requestmanager/RequestManagerViewModel.java

Link redmine:
https://dev.framgia.com/redmine/issues/135590

[Task #135590][Sprint 12] Assignment screen - Reslove Logic when Custom UI again 2

---

app/src/main/java/com/framgia/fdms/data/model/Producer.java
app/src/main/java/com/framgia/fdms/data/model/Status.java
app/src/main/java/com/framgia/fdms/data/source/CategoryDataSource.java
app/src/main/java/com/framgia/fdms/data/source/CategoryRepository.java
app/src/main/java/com/framgia/fdms/data/source/StatusDataSource.java
app/src/main/java/com/framgia/fdms/data/source/StatusRepository.java
app/src/main/java/com/framgia/fdms/data/source/remote/CategoryRemoteDataSource.java
app/src/main/java/com/framgia/fdms/data/source/remote/StatusRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/device/listdevice/ListDeviceContract.java
app/src/main/java/com/framgia/fdms/screen/device/listdevice/ListDevicePresenter.java
app/src/main/java/com/framgia/fdms/screen/device/listdevice/ListDeviceViewModel.java
app/src/main/java/com/framgia/fdms/screen/meetingroom/listmeetingroom/ListMeetingRoomViewModel.java
app/src/main/java/com/framgia/fdms/screen/meetingroom/listmeetingroom/MeetingRoomDialog.java
app/src/main/java/com/framgia/fdms/screen/new_selection/StatusSelectionActivity.java
app/src/main/java/com/framgia/fdms/screen/new_selection/StatusSelectionAdapter.java
app/src/main/java/com/framgia/fdms/screen/new_selection/StatusSelectionContract.java
app/src/main/java/com/framgia/fdms/screen/new_selection/StatusSelectionPresenter.java
app/src/main/java/com/framgia/fdms/screen/new_selection/StatusSelectionViewModel.java
app/src/main/java/com/framgia/fdms/screen/producer/ProducerAdapter.java
app/src/main/java/com/framgia/fdms/screen/producer/ProducerDialog.java
app/src/main/java/com/framgia/fdms/screen/producer/ProducerViewModel.java
app/src/main/java/com/framgia/fdms/utils/Constant.java
app/src/main/java/com/framgia/fdms/utils/navigator/Navigator.java
app/src/main/res/layout/activity_new_status_selection.xml

Redmine: https://dev.framgia.com/redmine/issues/135641ListDevice create filter model
- Start SelectionActivity to choose filter values.

[Sprint 12] Manager Devices screen - Custom UI >>> ListDevice create filter model

---

app/src/main/java/com/framgia/fdms/data/source/DeviceDataSource.java
app/src/main/java/com/framgia/fdms/data/source/DeviceRepository.java
app/src/main/java/com/framgia/fdms/data/source/remote/DeviceRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/device/listdevice/DeviceFilterModel.java
app/src/main/java/com/framgia/fdms/screen/device/listdevice/ListDeviceContract.java
app/src/main/java/com/framgia/fdms/screen/device/listdevice/ListDeviceFragment.java
app/src/main/java/com/framgia/fdms/screen/device/listdevice/ListDevicePresenter.java
app/src/main/java/com/framgia/fdms/screen/device/listdevice/ListDeviceViewModel.java
app/src/main/java/com/framgia/fdms/screen/new_selection/StatusSelectionContract.java
app/src/main/java/com/framgia/fdms/screen/new_selection/StatusSelectionPresenter.java
app/src/main/java/com/framgia/fdms/screen/new_selection/StatusSelectionViewModel.java
app/src/main/java/com/framgia/fdms/utils/Constant.java
app/src/main/java/com/framgia/fdms/utils/binding/BindingUtils.java
app/src/main/res/layout/filter_device.xml

Redmine: https://dev.framgia.com/redmine/issues/135642
- Add filter device by 
+ Filter Meeting Room,
+ Search Device
+ Search Staff Using

[Sprint 12] Manager Devices >>>> Api filter device by name, status, category, vendor, maker, meetingroom

---

app/src/main/java/com/framgia/fdms/screen/device/listdevice/ListDeviceViewModel.java
app/src/main/java/com/framgia/fdms/utils/binding/BindingUtils.java
app/src/main/res/layout/filter_device.xml
app/src/main/res/layout/fragment_list_device.xml

Redmine: https://dev.framgia.com/redmine/issues/135644

[Sprint 12] Fix filter screen

---

app/src/main/java/com/framgia/fdms/data/model/Status.java
app/src/main/java/com/framgia/fdms/screen/device/listdevice/ListDeviceViewModel.java
app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/DeviceUsingHistoryFilter.java
app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/DeviceUsingManagerContract.java
app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/DeviceUsingManagerFragment.java
app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/DeviceUsingManagerPresenter.java
app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/DeviceUsingManagerViewModel.java
app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/base/DeviceUsingBasePresenter.java
app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/base/DeviceUsingBaseViewModel.java
app/src/main/java/com/framgia/fdms/utils/binding/BindingUtils.java
app/src/main/res/layout/filter_device_using_history.xml
app/src/main/res/layout/fragment_device_using.xml

Redmine: https://dev.framgia.com/redmine/issues/135632
- Add device using history layout & filter layout XML

[Sprint 12] Using History Device screen - Desgin UI >>> Add device using history layout

---

app/src/main/java/com/framgia/fdms/data/model/DeviceUsingHistory.java
app/src/main/java/com/framgia/fdms/data/source/DeviceHistoryRepository.java
app/src/main/java/com/framgia/fdms/data/source/DeviceUsingHistoryDataSource.java
app/src/main/java/com/framgia/fdms/data/source/DeviceUsingHistoryRepository.java
app/src/main/java/com/framgia/fdms/data/source/api/service/FDMSApi.java
app/src/main/java/com/framgia/fdms/data/source/remote/DeviceUsingHistoryRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/DeviceUsingHistoryAdapter.java
app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/DeviceUsingManagerContract.java
app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/DeviceUsingManagerFragment.java
app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/DeviceUsingManagerPresenter.java
app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/DeviceUsingManagerViewModel.java
app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/base/DeviceUsingBasePresenter.java
app/src/main/java/com/framgia/fdms/utils/Constant.java

Redmine: https://dev.framgia.com/redmine/issues/135636

[Sprint 12] Using History Device screen - Call API Filter Using Device By Name's Staff or Email's Staff or Deivice Code

---

app/src/main/java/com/framgia/fdms/data/model/DeviceUsingHistory.java
app/src/main/java/com/framgia/fdms/data/source/api/error/BaseException.java
app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/DeviceUsingHistoryAdapter.java
app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/DeviceUsingManagerContract.java
app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/DeviceUsingManagerFragment.java
app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/DeviceUsingManagerViewModel.java
app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/base/DeviceUsingBaseViewModel.java
app/src/main/res/drawable/ic_down_arrow.xml
app/src/main/res/drawable/ic_down_arrow_black.xml
app/src/main/res/drawable/ic_down_arrow_white.xml
app/src/main/res/layout/item_device_using_history.xml
app/src/main/res/layout/item_group_device_history.xml
app/src/main/res/layout/item_group_user_device.xml

Redmine: https://dev.framgia.com/redmine/issues/135636

[Sprint 12] Using History Device screen  >> Edit item UI

---

app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/DeviceUsingHistoryAdapter.java
app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/DeviceUsingManagerContract.java
app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/DeviceUsingManagerFragment.java
app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/DeviceUsingManagerPresenter.java
app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/DeviceUsingManagerViewModel.java
app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/base/DeviceUsingBaseViewModel.java
app/src/main/java/com/framgia/fdms/screen/new_selection/SelectionType.java
app/src/main/java/com/framgia/fdms/utils/Constant.java
app/src/main/java/com/framgia/fdms/utils/navigator/Navigator.java
app/src/main/res/layout/fragment_device_using.xml

Redmine: https://dev.framgia.com/redmine/issues/135636

[Sprint 12] Using History Device screen >> Create Filter action

---

app/src/main/java/com/framgia/fdms/data/source/DeviceUsingHistoryDataSource.java
app/src/main/java/com/framgia/fdms/data/source/DeviceUsingHistoryRepository.java
app/src/main/java/com/framgia/fdms/data/source/remote/DeviceUsingHistoryRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/new_selection/StatusSelectionActivity.java
app/src/main/java/com/framgia/fdms/screen/new_selection/StatusSelectionPresenter.java
app/src/main/java/com/framgia/fdms/utils/Constant.java

redmine: https://dev.framgia.com/redmine/issues/135636

[Sprint 12] Using History Device screen >>> get Data status filter

---

app/src/main/java/com/framgia/fdms/screen/dashboard/DashboardContract.java
app/src/main/java/com/framgia/fdms/screen/dashboard/DashboardViewModel.java
app/src/main/java/com/framgia/fdms/screen/main/MainViewModel.java
app/src/main/res/layout/activity_newmain.xml
app/src/main/res/layout/fragment_dashboard.xml

Redmine: https://dev.framgia.com/redmine/issues/137666

[Sprint12] - Direct notification screen

---

app/src/main/java/com/framgia/fdms/screen/device/listdevice/ListDeviceViewModel.java
app/src/main/java/com/framgia/fdms/screen/main/MainViewModel.java
app/src/main/java/com/framgia/fdms/screen/producer/ProducerAdapter.java
app/src/main/java/com/framgia/fdms/screen/request/userrequest/UserRequestViewModel.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/RequestDetailPresenter.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/RequestDetailViewModel.java

Redmine: https://dev.framgia.com/redmine/issues/137790

[Sprint12] - Fix request detail scren

---

app/src/main/java/com/framgia/fdms/data/source/StatusDataSource.java
app/src/main/java/com/framgia/fdms/data/source/StatusRepository.java
app/src/main/java/com/framgia/fdms/data/source/remote/StatusRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/new_selection/SelectionType.java
app/src/main/java/com/framgia/fdms/screen/new_selection/StatusSelectionActivity.java
app/src/main/java/com/framgia/fdms/screen/new_selection/StatusSelectionContract.java
app/src/main/java/com/framgia/fdms/screen/new_selection/StatusSelectionPresenter.java
app/src/main/java/com/framgia/fdms/screen/request/requestmanager/RequestManagerContract.java
app/src/main/java/com/framgia/fdms/screen/request/requestmanager/RequestManagerPresenter.java
app/src/main/java/com/framgia/fdms/screen/request/requestmanager/RequestManagerViewModel.java

Redmine: https://dev.framgia.com/redmine/issues/137858

[Sprint12] - Fix Logic Request Manager >> StatusSelection Add status filter request

---

app/src/main/java/com/framgia/fdms/screen/request/userrequest/UserRequestContract.java
app/src/main/java/com/framgia/fdms/screen/request/userrequest/UserRequestFragment.java
app/src/main/java/com/framgia/fdms/screen/request/userrequest/UserRequestPresenter.java
app/src/main/java/com/framgia/fdms/screen/request/userrequest/UserRequestViewModel.java
app/src/main/java/com/framgia/fdms/screen/returndevice/ReturnDeviceViewModel.java

Redmine: https://dev.framgia.com/redmine/issues/137858

[Sprint12] - UserManager Request Screen >>> Change Filter to new Activity

---

app/src/main/java/com/framgia/fdms/data/model/Device.java
app/src/main/java/com/framgia/fdms/data/model/DeviceUsingHistory.java
app/src/main/java/com/framgia/fdms/data/source/api/service/FDMSApi.java
app/src/main/java/com/framgia/fdms/data/source/remote/DeviceUsingHistoryRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/DeviceUsingHistoryFilter.java
app/src/main/java/com/framgia/fdms/utils/Constant.java
app/src/main/java/com/framgia/fdms/utils/Utils.java
app/src/main/res/layout/item_device_using_history.xml
app/src/main/res/layout/item_group_user_device.xml

- Redmine: https://dev.framgia.com/redmine/issues/135636
- Update Api to the server's lastest document

[Sprint 12] Using History Device screen >>> Update api get using device history by server

---

app/src/main/java/com/framgia/fdms/data/model/Device.java
app/src/main/java/com/framgia/fdms/screen/devicecreation/CreateDeviceContract.java
app/src/main/java/com/framgia/fdms/screen/devicecreation/CreateDeviceViewModel.java
app/src/main/res/layout/activity_createdevice.xml

Task: resolve logic create device
link redmine: https://dev.framgia.com/redmine/issues/135605

fix resolve logic create device

---

app/src/main/java/com/framgia/fdms/data/model/User.java
app/src/main/java/com/framgia/fdms/data/source/UserDataSource.java
app/src/main/java/com/framgia/fdms/data/source/UserRepository.java
app/src/main/java/com/framgia/fdms/data/source/api/service/FDMSApi.java
app/src/main/java/com/framgia/fdms/data/source/remote/UserRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/profile/ProfileContract.java
app/src/main/java/com/framgia/fdms/screen/profile/ProfileFragment.java
app/src/main/java/com/framgia/fdms/screen/profile/ProfilePresenter.java
app/src/main/java/com/framgia/fdms/screen/profile/ProfileViewModel.java
app/src/main/res/layout/fragment_profile.xml

Task: Call API update profile
Link redmine: https://dev.framgia.com/redmine/issues/135594

[Sprint 12] Call API update profile

---

app/src/main/java/com/framgia/fdms/screen/device/mydevice/MyDeviceContract.java
app/src/main/java/com/framgia/fdms/screen/device/mydevice/MyDeviceFragment.java
app/src/main/java/com/framgia/fdms/screen/device/mydevice/MyDevicePresenter.java
app/src/main/java/com/framgia/fdms/screen/device/mydevice/MyDeviceViewModel.java
app/src/main/java/com/framgia/fdms/screen/device/mydevice/mydevicedetail/MyDeviceDetailContract.java
app/src/main/java/com/framgia/fdms/screen/device/mydevice/mydevicedetail/MyDeviceDetailFragment.java
app/src/main/java/com/framgia/fdms/screen/device/mydevice/mydevicedetail/MyDeviceDetailPresenter.java
app/src/main/java/com/framgia/fdms/screen/device/mydevice/mydevicedetail/MyDeviceDetailViewModel.java
app/src/main/java/com/framgia/fdms/screen/main/MainViewModel.java
app/src/main/res/layout/fragment_my_device.xml
app/src/main/res/layout/fragment_my_device_detail.xml

Redmine: https://dev.framgia.com/redmine/issues/138389
- Add MyDevice Fragment with Viewpager to display MyDeviceDetailFragment with 3 tab all, using, return
- Add MyDeviceDetailFragment with RecyclerView to display User Device

[Sprint 12] My Device Fragment >>> ADD Fragment

---

app/src/main/java/com/framgia/fdms/screen/device/mydevice/MyDeviceFragment.java
app/src/main/java/com/framgia/fdms/screen/device/mydevice/MyDevicePagerAdapter.java
app/src/main/java/com/framgia/fdms/screen/device/mydevice/MyDeviceViewModel.java
app/src/main/java/com/framgia/fdms/screen/device/mydevice/mydevicedetail/MyDeviceDetailFragment.java
app/src/main/java/com/framgia/fdms/screen/device/mydevice/mydevicedetail/MyDeviceType.java
app/src/main/res/layout/fragment_my_device.xml
app/src/main/res/values/strings.xml

- Redmine: https://dev.framgia.com/redmine/issues/138389
- Add Pager Adapter for ViewPager

[Sprint12] - Device Screen >>>  Add Viewpager Adapter

---

app/src/main/java/com/framgia/fdms/data/source/api/request/RequestCreatorRequest.java
app/src/main/java/com/framgia/fdms/data/source/remote/RequestRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/requestcreation/RequestCreationActivity.java
app/src/main/java/com/framgia/fdms/screen/requestcreation/RequestCreationContract.java
app/src/main/java/com/framgia/fdms/screen/requestcreation/RequestCreationPresenter.java
app/src/main/java/com/framgia/fdms/screen/requestcreation/RequestCreationViewModel.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionActivity.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionContract.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionPresenter.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionType.java
app/src/main/java/com/framgia/fdms/utils/Constant.java
app/src/main/res/layout/activity_request_creation.xml
app/src/main/res/values/strings.xml

Task : [Sprint 12] - Update Request Screen
Link redmine: https://dev.framgia.com/redmine/issues/138234

[Sprint 12] Feature update request screen

---

app/src/main/java/com/framgia/fdms/data/source/DeviceDataSource.java
app/src/main/java/com/framgia/fdms/data/source/DeviceRepository.java
app/src/main/java/com/framgia/fdms/data/source/api/service/FDMSApi.java
app/src/main/java/com/framgia/fdms/data/source/remote/DeviceRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/device/mydevice/mydevicedetail/MyDeviceDetailContract.java
app/src/main/java/com/framgia/fdms/screen/device/mydevice/mydevicedetail/MyDeviceDetailFragment.java
app/src/main/java/com/framgia/fdms/screen/device/mydevice/mydevicedetail/MyDeviceDetailPresenter.java
app/src/main/java/com/framgia/fdms/screen/device/mydevice/mydevicedetail/MyDeviceDetailViewModel.java

- Redmine: https://dev.framgia.com/redmine/issues/138389
- Call Api get user device

[Sprint 12] My Device screen get data

---

app/src/main/java/com/framgia/fdms/screen/device/mydevice/MyDeviceViewModel.java
app/src/main/java/com/framgia/fdms/screen/device/mydevice/mydevicedetail/MyDeviceDetailAdapter.java
app/src/main/java/com/framgia/fdms/screen/device/mydevice/mydevicedetail/MyDeviceDetailContract.java
app/src/main/java/com/framgia/fdms/screen/device/mydevice/mydevicedetail/MyDeviceDetailPresenter.java
app/src/main/java/com/framgia/fdms/screen/device/mydevice/mydevicedetail/MyDeviceDetailViewModel.java
app/src/main/java/com/framgia/fdms/utils/binding/BindingUtils.java
app/src/main/res/layout/fragment_my_device.xml
app/src/main/res/layout/fragment_my_device_detail.xml
app/src/main/res/layout/item_my_device.xml
app/src/main/res/layout/nav_header_main.xml
app/src/main/res/values/strings.xml

- Redmine: https://dev.framgia.com/redmine/issues/138389
- Create Adapter and display data to UI

[Sprint 12] My device update ui

---

app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/DeviceUsingHistoryFilter.java
app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/DeviceUsingManagerPresenter.java
app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/DeviceUsingManagerViewModel.java
app/src/main/java/com/framgia/fdms/utils/binding/BindingUtils.java
app/src/main/res/layout/fragment_device_using.xml
app/src/main/res/layout/item_assignment.xml

- Redmine: https://dev.framgia.com/redmine/issues/138705
- Add loadmore data in device using histoy screen

[Sprint 12] Device Using History Screen > Load more data

---

app/src/main/java/com/framgia/fdms/data/source/DeviceReturnDataSource.java
app/src/main/java/com/framgia/fdms/data/source/DeviceReturnRepository.java
app/src/main/java/com/framgia/fdms/data/source/StatusDataSource.java
app/src/main/java/com/framgia/fdms/data/source/StatusRepository.java
app/src/main/java/com/framgia/fdms/data/source/api/service/FDMSApi.java
app/src/main/java/com/framgia/fdms/data/source/remote/DeviceReturnRemoteDataSource.java
app/src/main/java/com/framgia/fdms/data/source/remote/StatusRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/returndevice/DeviceReturnAdapter.java
app/src/main/java/com/framgia/fdms/screen/returndevice/ReturnDeviceContract.java
app/src/main/java/com/framgia/fdms/screen/returndevice/ReturnDevicePresenter.java
app/src/main/java/com/framgia/fdms/screen/returndevice/ReturnDeviceViewModel.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionActivity.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionContract.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionPresenter.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionType.java
app/src/main/java/com/framgia/fdms/utils/Constant.java
app/src/main/res/layout/activity_return_device.xml

Link redmine: https://dev.framgia.com/redmine/issues/135646

[Sprint 12] Feature return device

---

app/src/main/java/com/framgia/fdms/data/source/DeviceDataSource.java
app/src/main/java/com/framgia/fdms/data/source/DeviceGroupDataSource.java
app/src/main/java/com/framgia/fdms/data/source/DeviceGroupRepository.java
app/src/main/java/com/framgia/fdms/data/source/DeviceRepository.java
app/src/main/java/com/framgia/fdms/data/source/api/service/FDMSApi.java
app/src/main/java/com/framgia/fdms/data/source/remote/CategoryRemoteDataSource.java
app/src/main/java/com/framgia/fdms/data/source/remote/DeviceGroupRemoteDataSource.java
app/src/main/java/com/framgia/fdms/data/source/remote/DeviceRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/assignment/AssignmentViewModel.java
app/src/main/java/com/framgia/fdms/screen/device/listdevice/ListDeviceFragment.java
app/src/main/java/com/framgia/fdms/screen/device/listdevice/ListDeviceViewModel.java
app/src/main/java/com/framgia/fdms/screen/main/MainActivity.java
app/src/main/java/com/framgia/fdms/screen/meetingroom/detailmeetingroom/ItemListDeviceViewModel.java
app/src/main/java/com/framgia/fdms/screen/meetingroom/detailmeetingroom/ListDeviceAdapter.java
app/src/main/java/com/framgia/fdms/screen/notification/NotificationContract.java
app/src/main/java/com/framgia/fdms/screen/notification/NotificationPresenter.java
app/src/main/java/com/framgia/fdms/screen/notification/NotificationViewModel.java
app/src/main/java/com/framgia/fdms/screen/producer/ProducerContract.java
app/src/main/java/com/framgia/fdms/screen/producer/ProducerPresenter.java
app/src/main/java/com/framgia/fdms/screen/producer/ProducerViewModel.java
app/src/main/java/com/framgia/fdms/screen/request/requestmanager/RequestManagerViewModel.java
app/src/main/java/com/framgia/fdms/screen/requestcreation/RequestCreationContract.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/RequestDetailActivity.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/RequestDetailViewModel.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionActivity.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionAdapter.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionPresenter.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionViewModel.java
app/src/main/res/layout/fragment_list_device.xml
app/src/main/res/values/strings.xml

- Redmine: https://dev.framgia.com/redmine/issues/138834
- Get data device groups

[Sprint 12] - Manager Device Group get all device group, Re-format code

---

app/src/main/java/com/framgia/fdms/BaseFragmentModel.java
app/src/main/java/com/framgia/fdms/data/source/RequestRepositoryContract.java
app/src/main/java/com/framgia/fdms/data/source/remote/RequestRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/device/listdevice/ListDeviceContract.java
app/src/main/java/com/framgia/fdms/screen/device/listdevice/ListDevicePresenter.java
app/src/main/java/com/framgia/fdms/screen/device/listdevice/ListDeviceViewModel.java
app/src/main/java/com/framgia/fdms/screen/device/mydevice/mydevicedetail/MyDeviceDetailContract.java
app/src/main/java/com/framgia/fdms/screen/device/mydevice/mydevicedetail/MyDeviceDetailPresenter.java
app/src/main/java/com/framgia/fdms/screen/device/mydevice/mydevicedetail/MyDeviceDetailViewModel.java
app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/DeviceUsingManagerContract.java
app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/DeviceUsingManagerPresenter.java
app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/DeviceUsingManagerViewModel.java
app/src/main/java/com/framgia/fdms/screen/meetingroom/detailmeetingroom/DetailMeetingRoomContract.java
app/src/main/java/com/framgia/fdms/screen/meetingroom/detailmeetingroom/DetailMeetingRoomPresenter.java
app/src/main/java/com/framgia/fdms/screen/meetingroom/detailmeetingroom/DetailMeetingRoomViewModel.java
app/src/main/java/com/framgia/fdms/screen/meetingroom/listmeetingroom/ListMeetingRoomContract.java
app/src/main/java/com/framgia/fdms/screen/meetingroom/listmeetingroom/ListMeetingRoomPresenter.java
app/src/main/java/com/framgia/fdms/screen/meetingroom/listmeetingroom/ListMeetingRoomViewModel.java
app/src/main/java/com/framgia/fdms/screen/producer/ProducerContract.java
app/src/main/java/com/framgia/fdms/screen/producer/ProducerPresenter.java
app/src/main/java/com/framgia/fdms/screen/producer/ProducerViewModel.java
app/src/main/java/com/framgia/fdms/screen/request/requestmanager/RequestManagerContract.java
app/src/main/java/com/framgia/fdms/screen/request/requestmanager/RequestManagerPresenter.java
app/src/main/java/com/framgia/fdms/screen/request/requestmanager/RequestManagerViewModel.java
app/src/main/java/com/framgia/fdms/screen/request/userrequest/UserRequestContract.java
app/src/main/java/com/framgia/fdms/screen/request/userrequest/UserRequestPresenter.java
app/src/main/java/com/framgia/fdms/screen/request/userrequest/UserRequestViewModel.java
app/src/main/res/layout/activity_detail_meeting_room.xml
app/src/main/res/layout/fragment_request_manager.xml

- Fix load more list device screen
- Fix load more producer screen
- Fix Loadmore meeting room, meeting room detail
- User Request && Manager Request

Fix load more in screen

---

app/src/main/java/com/framgia/fdms/data/model/Device.java
app/src/main/java/com/framgia/fdms/screen/returndevice/ReturnDeviceViewModel.java
app/src/main/res/values/strings.xml

Link redmine: https://dev.framgia.com/redmine/issues/138977

[Sprint 12]Feature Qr-Bar Code return device

---

app/src/main/java/com/framgia/fdms/screen/returndevice/ReturnDeviceContract.java
app/src/main/java/com/framgia/fdms/screen/returndevice/ReturnDevicePresenter.java
app/src/main/java/com/framgia/fdms/screen/returndevice/ReturnDeviceViewModel.java

- Redmine: https://dev.framgia.com/redmine/issues/139539

[Sprint 12] update return device screen

---

app/src/main/java/com/framgia/fdms/screen/dashboard/dashboarddetail/DashBoardDetailViewModel.java
app/src/main/java/com/framgia/fdms/utils/binding/BindingUtils.java

- Redmine: https://dev.framgia.com/redmine/issues/139112

ref bug#139112: change title when click dashboard chart item

---

app/src/main/java/com/framgia/fdms/data/model/Producer.java
app/src/main/java/com/framgia/fdms/data/source/CategoryDataSource.java
app/src/main/java/com/framgia/fdms/data/source/CategoryRepository.java
app/src/main/java/com/framgia/fdms/data/source/api/service/FDMSApi.java
app/src/main/java/com/framgia/fdms/data/source/remote/CategoryRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/meetingroom/listmeetingroom/ListMeetingRoomViewModel.java
app/src/main/java/com/framgia/fdms/screen/producer/ProducerContract.java
app/src/main/java/com/framgia/fdms/screen/producer/ProducerDialog.java
app/src/main/java/com/framgia/fdms/screen/producer/ProducerDialogContract.java
app/src/main/java/com/framgia/fdms/screen/producer/ProducerPresenter.java
app/src/main/java/com/framgia/fdms/screen/producer/ProducerViewModel.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionActivity.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionPresenter.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionType.java
app/src/main/java/com/framgia/fdms/utils/Constant.java
app/src/main/res/layout/dialog_confirm_producer.xml
app/src/main/res/values/strings.xml

Add: https://dev.framgia.com/redmine/issues/138994
Edit: https://dev.framgia.com/redmine/issues/138995
Delete: https://dev.framgia.com/redmine/issues/138996

[Sprint 12] Manage device category (Add, edit, delete)

---

app/src/main/java/com/framgia/fdms/data/source/StatusDataSource.java
app/src/main/java/com/framgia/fdms/data/source/StatusRepository.java
app/src/main/java/com/framgia/fdms/data/source/api/service/FDMSApi.java
app/src/main/java/com/framgia/fdms/data/source/remote/StatusRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/devicecreation/CreateDeviceViewModel.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionActivity.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionContract.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionPresenter.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionViewModel.java
app/src/main/res/layout/fragment_profile.xml

Link redmine:  https://dev.framgia.com/redmine/issues/140106

[Sprint 12] Hide edit profile function + Fix Selection Producer

---

app/src/main/java/com/framgia/fdms/data/model/DeviceHistoryDetail.java
app/src/main/java/com/framgia/fdms/data/model/DeviceHistoryInfo.java
app/src/main/java/com/framgia/fdms/data/source/DeviceDataSource.java
app/src/main/java/com/framgia/fdms/data/source/DeviceRepository.java
app/src/main/java/com/framgia/fdms/data/source/api/service/FDMSApi.java
app/src/main/java/com/framgia/fdms/data/source/remote/DeviceGroupRemoteDataSource.java
app/src/main/java/com/framgia/fdms/data/source/remote/DeviceRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/history/DeviceDetailHistoryContract.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/history/DeviceDetailHistoryFragment.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/history/DeviceDetailHistoryPresenter.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/history/DeviceDetailHistoryViewModel.java
app/src/main/res/layout/fragment_history_detail.xml
app/src/main/res/layout/item_history_detail.xml

Redmine 
- https://dev.framgia.com/redmine/issues/138835
- https://dev.framgia.com/redmine/issues/138836
- https://dev.framgia.com/redmine/issues/138837

[Sprint 12] add, edit, delete device group function

---

app/src/main/java/com/framgia/fdms/screen/dashboard/DashboardViewModel.java
app/src/main/java/com/framgia/fdms/screen/dashboard/dashboarddetail/DashBoardDetailViewModel.java
app/src/main/java/com/framgia/fdms/screen/request/requestmanager/RequestManagerViewModel.java
app/src/main/java/com/framgia/fdms/screen/request/userrequest/UserRequestViewModel.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/RequestDetailActivity.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/RequestDetailContract.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/RequestDetailPagerAdapter.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/RequestDetailPresenter.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/RequestDetailViewModel.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/information/RequestInformationContract.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/information/RequestInformationFragment.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/information/RequestInformationPresenter.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/information/RequestInformationViewModel.java
app/src/main/java/com/framgia/fdms/utils/binding/BindingUtils.java
app/src/main/res/layout/activity_request_detail.xml
app/src/main/res/layout/fragment_request_information.xml
app/src/main/res/values/strings.xml

Link redmine: https://dev.framgia.com/redmine/issues/139166

Fix missing device assignment (custom UI)

---

app/src/main/java/com/framgia/fdms/data/model/DeviceHistoryDetail.java
app/src/main/java/com/framgia/fdms/data/model/DeviceHistoryInfo.java
app/src/main/java/com/framgia/fdms/data/source/remote/DeviceRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/history/DeviceDetailHistoryAdapter.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/history/DeviceDetailHistoryContract.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/history/DeviceDetailHistoryPresenter.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/history/DeviceDetailHistoryViewModel.java
app/src/main/res/layout/fragment_history_detail.xml
app/src/main/res/layout/item_history_detail.xml

Redmine
- https://dev.framgia.com/redmine/issues/138171

[Sprint 12] Device Detail show history device.

---

app/src/main/java/com/framgia/fdms/data/model/Device.java
app/src/main/java/com/framgia/fdms/data/source/api/service/FDMSApi.java
app/src/main/java/com/framgia/fdms/data/source/remote/DeviceRemoteDataSource.java
app/src/main/java/com/framgia/fdms/data/source/remote/RequestRemoteDataSource.java
app/src/main/java/com/framgia/fdms/data/source/remote/StatusRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/assignment/AssignmentViewModel.java
app/src/main/java/com/framgia/fdms/screen/device/listdevice/ListDeviceViewModel.java
app/src/main/java/com/framgia/fdms/screen/deviceselection/DeviceSelectionActivity.java
app/src/main/java/com/framgia/fdms/screen/deviceselection/DeviceSelectionPresenter.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionContract.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionPresenter.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionViewModel.java
app/src/main/java/com/framgia/fdms/utils/Constant.java
app/src/main/java/com/framgia/fdms/utils/Utils.java

- Redmine: https://dev.framgia.com/redmine/issues/139000

[Sprint 12] - Function assign device for new member

---

app/src/main/java/com/framgia/fdms/data/model/Device.java
app/src/main/java/com/framgia/fdms/data/source/remote/DeviceRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/device/listdevice/DeviceFilterModel.java
app/src/main/java/com/framgia/fdms/screen/devicecreation/CreateDeviceContract.java
app/src/main/java/com/framgia/fdms/screen/devicecreation/CreateDeviceViewModel.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/DeviceDetailContract.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/DeviceDetailViewModel.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/infomation/DeviceInfomationContract.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/infomation/DeviceInfomationFragment.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/infomation/DeviceInfomationViewModel.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionActivity.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionContract.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionPresenter.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionViewModel.java
app/src/main/java/com/framgia/fdms/utils/Constant.java
app/src/main/res/drawable/ic_delete_forever_black_24dp.xml
app/src/main/res/drawable/ic_edit_black_24dp.xml
app/src/main/res/layout/activity_createdevice.xml
app/src/main/res/layout/activity_device_detail.xml
app/src/main/res/values/strings.xml

https://dev.framgia.com/redmine/issues/140488

[Sprint 12] - Fix edit device

---

app/src/main/java/com/framgia/fdms/data/source/DeviceDataSource.java
app/src/main/java/com/framgia/fdms/data/source/DeviceRepository.java
app/src/main/java/com/framgia/fdms/data/source/api/service/FDMSApi.java
app/src/main/java/com/framgia/fdms/data/source/remote/DeviceRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/device/listdevice/ListDeviceViewModel.java
app/src/main/java/com/framgia/fdms/screen/devicecreation/CreateDevicePresenter.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/DeviceDetailActivity.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/DeviceDetailContract.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/DeviceDetailPresenter.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/DeviceDetailViewModel.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/infomation/DeviceInfomationContract.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/infomation/DeviceInfomationFragment.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/infomation/DeviceInfomationPresenter.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/infomation/DeviceInfomationViewModel.java
app/src/main/java/com/framgia/fdms/utils/Constant.java
app/src/main/java/com/framgia/fdms/utils/binding/BindingUtils.java
app/src/main/res/layout/activity_device_detail.xml

https://dev.framgia.com/redmine/issues/140489

[Sprint 12] Delete device

---

app/src/main/java/com/framgia/fdms/screen/main/MainViewModel.java
app/src/main/res/values/strings.xml

Redmine: https://dev.framgia.com/redmine/issues/140951
- Change app name to FGAS
- Mở app chưa select vào icon dashboard
- Title app khi mở chưa phải là dashboard

[Sprint 12] Update home screen

---

app/src/main/java/com/framgia/fdms/screen/device/listdevice/ListDeviceAdapter.java
app/src/main/java/com/framgia/fdms/screen/device/listdevice/ListDeviceViewModel.java
app/src/main/java/com/framgia/fdms/screen/devicecreation/CreateDeviceActivity.java
app/src/main/java/com/framgia/fdms/screen/devicecreation/CreateDeviceContract.java
app/src/main/java/com/framgia/fdms/screen/devicecreation/CreateDevicePresenter.java
app/src/main/java/com/framgia/fdms/screen/devicecreation/CreateDeviceViewModel.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/DeviceDetailActivity.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/infomation/DeviceInfomationViewModel.java
app/src/main/java/com/framgia/fdms/utils/Constant.java
app/src/main/res/layout/activity_createdevice.xml
app/src/main/res/layout/fragment_list_device.xml
app/src/main/res/values/strings.xml

https://dev.framgia.com/redmine/issues/138170
- update device vừa được tạo vào màn hình listdevice
- xóa device khỏi listdevice khi delete success

[Sprint 12] Fix create device

---

app/src/main/java/com/framgia/fdms/screen/request/userrequest/UserRequestContract.java
app/src/main/java/com/framgia/fdms/screen/request/userrequest/UserRequestPresenter.java
app/src/main/java/com/framgia/fdms/screen/request/userrequest/UserRequestViewModel.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionActivity.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionContract.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionPresenter.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionType.java
app/src/main/java/com/framgia/fdms/utils/Constant.java
app/src/main/res/layout/fragment_profile.xml
app/src/main/res/layout/fragment_request_information.xml
app/src/main/res/layout/fragment_user_request.xml
app/src/main/res/values/strings.xml

Fix load list + load more my request
Fix UI request detail, my request
Link redmine: https://dev.framgia.com/redmine/issues/140945

[Sprint 2]Fix request screen

---

app/src/main/java/com/framgia/fdms/screen/devicedetail/usinghistory/DeviceUsingAdapter.java
app/src/main/java/com/framgia/fdms/screen/profile/export/ExportDialogFragment.java
app/src/main/java/com/framgia/fdms/screen/profile/export/ExportPresenter.java
app/src/main/java/com/framgia/fdms/utils/Utils.java
app/src/main/java/com/framgia/fdms/utils/binding/BindingUtils.java
app/src/main/res/layout/device_information.xml
app/src/main/res/layout/item_device_using_history.xml
app/src/main/res/layout/item_history_detail.xml
app/src/main/res/layout/item_my_device.xml
app/src/main/res/values-ja/strings.xml
app/src/main/res/values-vi/strings.xml
app/src/main/res/values/strings.xml

#141763 Device list - Reformat date Mutil Language
https://dev.framgia.com/redmine/issues/141763
#141753 Dashboard -Change title Requests Overview
https://dev.framgia.com/redmine/issues/141753

[BUG] #141763 Device list - Reformat date Mutil Language, Bug #141753 Dashboard -Change title Requests Overview

---

app/src/main/java/com/framgia/fdms/data/source/remote/StatusRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionActivity.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionAdapter.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionContract.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionPresenter.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionViewModel.java
app/src/main/java/com/framgia/fdms/utils/Constant.java

https://dev.framgia.com/redmine/issues/141578

[BUG] #141578 Fix search loadmore selection

---

app/src/main/java/com/framgia/fdms/data/source/remote/DeviceUsingHistoryRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/DeviceUsingHistoryFilter.java
app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/DeviceUsingManagerContract.java
app/src/main/java/com/framgia/fdms/screen/deviceusingmanager/DeviceUsingManagerViewModel.java
app/src/main/java/com/framgia/fdms/screen/request/requestmanager/RequestManagerViewModel.java
app/src/main/java/com/framgia/fdms/screen/request/userrequest/UserRequestViewModel.java
app/src/main/java/com/framgia/fdms/screen/requestcreation/RequestCreationPresenter.java
app/src/main/java/com/framgia/fdms/screen/requestcreation/RequestCreationViewModel.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionActivity.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionAdapter.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionPresenter.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionType.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionViewModel.java
app/src/main/java/com/framgia/fdms/utils/Constant.java
app/src/main/res/layout/activity_request_creation.xml
app/src/main/res/layout/filter_device_using_history.xml
app/src/main/res/layout/fragment_request_information.xml
app/src/main/res/layout/fragment_request_manager.xml
app/src/main/res/values-ja/strings.xml
app/src/main/res/values-vi/strings.xml
app/src/main/res/values/strings.xml

https://dev.framgia.com/redmine/issues/141264
Thêm Filter theo branch của staff ở tran Device using history

[BUG]  Add "Branch" filter for device using history screen

---

app/src/main/java/com/framgia/fdms/data/source/remote/DeviceRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/device/listdevice/DeviceFilterModel.java
app/src/main/java/com/framgia/fdms/screen/device/listdevice/ListDeviceContract.java
app/src/main/java/com/framgia/fdms/screen/device/listdevice/ListDeviceViewModel.java
app/src/main/java/com/framgia/fdms/screen/devicecreation/CreateDevicePresenter.java
app/src/main/java/com/framgia/fdms/screen/devicecreation/CreateDeviceViewModel.java
app/src/main/java/com/framgia/fdms/screen/producer/ProducerViewModel.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionActivity.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionAdapter.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionPresenter.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionType.java
app/src/main/java/com/framgia/fdms/utils/Constant.java
app/src/main/java/com/framgia/fdms/utils/binding/BindingUtils.java
app/src/main/res/layout/filter_device.xml

https://dev.framgia.com/redmine/issues/142090
Thêm Filter theo branch ở list device

[BUG] Add branch filter device

---

app/src/main/res/layout/activity_request_creation.xml

Redmine: https://dev.framgia.com/redmine/issues/142284

[BUG] - Create request Verify the appropriate error message displays when user input Title > 50 characters

---

app/src/main/java/com/framgia/fdms/data/model/Device.java
app/src/main/java/com/framgia/fdms/screen/device/mydevice/mydevicedetail/MyDeviceDetailPresenter.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/DeviceDetailPresenter.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/DeviceDetailViewModel.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/history/DeviceDetailHistoryContract.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/history/DeviceDetailHistoryFragment.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/history/DeviceDetailHistoryPresenter.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/history/DeviceDetailHistoryViewModel.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/infomation/DeviceInfomationContract.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/infomation/DeviceInfomationFragment.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/infomation/DeviceInfomationViewModel.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/usinghistory/DeviceUsingHistoryContract.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/usinghistory/DeviceUsingHistoryFragment.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/usinghistory/DeviceUsingHistoryPresenter.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/usinghistory/DeviceUsingHistoryViewModel.java
app/src/main/res/layout/activity_request_creation.xml
app/src/main/res/layout/fragment_request_information.xml

Redmine: https://dev.framgia.com/redmine/issues/142479

[BUG] Fix detail device screen

---

app/src/main/java/com/framgia/fdms/screen/devicecreation/CreateDeviceActivity.java
app/src/main/java/com/framgia/fdms/screen/devicecreation/CreateDevicePresenter.java
app/src/main/java/com/framgia/fdms/screen/devicecreation/CreateDeviceViewModel.java
app/src/main/java/com/framgia/fdms/utils/binding/BindingUtils.java
app/src/main/res/layout/activity_createdevice.xml
app/src/main/res/values-ja/strings.xml
app/src/main/res/values-vi/strings.xml
app/src/main/res/values/strings.xml

Redmine: https://dev.framgia.com/redmine/issues/142303
1. Verify status of device is "Using" if that device was used by meeting room
2. Verify error message displays when user select checkbox "Is meetting room" but don't select meeting room
3. Mong muốn format text ngay sau khi nhập liệu

[BUG] - Add new devide logic

---

app/src/main/java/com/framgia/fdms/data/model/Request.java
app/src/main/java/com/framgia/fdms/screen/request/requestmanager/RequestManagerViewModel.java
app/src/main/java/com/framgia/fdms/screen/request/userrequest/UserRequestViewModel.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/information/RequestInformationViewModel.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionActivity.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionAdapter.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionPresenter.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionType.java
app/src/main/res/layout/activity_request_creation.xml
app/src/main/res/layout/fragment_request_information.xml

https://dev.framgia.com/redmine/issues/142518

[BUG] Fix request screen

---

app/src/main/java/com/framgia/fdms/screen/requestdetail/information/RequestInformationContract.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/information/RequestInformationPresenter.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/information/RequestInformationViewModel.java
app/src/main/res/layout/edittext_input.xml
app/src/main/res/layout/fragment_request_information.xml

Redmine: https://dev.framgia.com/redmine/issues/142285

[BUG] - Edit request - Verify Title field is required fields

---

app/src/main/java/com/framgia/fdms/data/source/RequestDataSource.java
app/src/main/java/com/framgia/fdms/data/source/RequestRepository.java
app/src/main/java/com/framgia/fdms/data/source/RequestRepositoryContract.java
app/src/main/java/com/framgia/fdms/data/source/api/service/FDMSApi.java
app/src/main/java/com/framgia/fdms/data/source/remote/RequestRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/request/requestmanager/RequestManagerContract.java
app/src/main/java/com/framgia/fdms/screen/request/requestmanager/RequestManagerPresenter.java
app/src/main/java/com/framgia/fdms/screen/request/requestmanager/RequestManagerViewModel.java
app/src/main/java/com/framgia/fdms/screen/request/userrequest/UserRequestContract.java
app/src/main/java/com/framgia/fdms/screen/request/userrequest/UserRequestPresenter.java
app/src/main/java/com/framgia/fdms/screen/request/userrequest/UserRequestViewModel.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/information/RequestInformationContract.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/information/RequestInformationPresenter.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/information/RequestInformationViewModel.java
app/src/main/res/values-ja/strings.xml
app/src/main/res/values-vi/strings.xml
app/src/main/res/values/strings.xml

- Update api cancel request
- https://dev.framgia.com/redmine/issues/141148

Call Api cancel request

---

app/src/main/java/com/framgia/fdms/data/model/Device.java
app/src/main/java/com/framgia/fdms/data/source/remote/DeviceRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/devicecreation/CreateDeviceActivity.java
app/src/main/java/com/framgia/fdms/screen/devicecreation/CreateDeviceContract.java
app/src/main/java/com/framgia/fdms/screen/devicecreation/CreateDevicePresenter.java
app/src/main/java/com/framgia/fdms/screen/devicecreation/CreateDeviceViewModel.java
app/src/main/res/layout/activity_createdevice.xml

https://dev.framgia.com/redmine/issues/143149
Bổ sung branch, vendor, maker, meeting room trong phần edit device

[BUG] Edit device fix

---

app/src/main/java/com/framgia/fdms/screen/producer/ProducerDialog.java
app/src/main/java/com/framgia/fdms/screen/producer/ProducerDialogContract.java
app/src/main/java/com/framgia/fdms/screen/producer/ProducerFragment.java
app/src/main/java/com/framgia/fdms/screen/producer/ProducerViewModel.java
app/src/main/java/com/framgia/fdms/utils/Constant.java
app/src/main/java/com/framgia/fdms/utils/binding/BindingUtils.java
app/src/main/res/layout/dialog_confirm_producer.xml
app/src/main/res/layout/fragment_producer.xml
app/src/main/res/values-ja/strings.xml
app/src/main/res/values-vi/strings.xml
app/src/main/res/values/strings.xml

Redmine: https://dev.framgia.com/redmine/issues/142309

[BUG] Ref Fix UI at vendor, marker, meeting rom

---

app/src/main/java/com/framgia/fdms/data/model/Request.java
app/src/main/java/com/framgia/fdms/data/source/StatusDataSource.java
app/src/main/java/com/framgia/fdms/data/source/StatusRepository.java
app/src/main/java/com/framgia/fdms/data/source/remote/RequestRemoteDataSource.java
app/src/main/java/com/framgia/fdms/data/source/remote/StatusRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/devicecreation/CreateDeviceViewModel.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/information/RequestInformationViewModel.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionActivity.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionAdapter.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionContract.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionPresenter.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionType.java
app/src/main/java/com/framgia/fdms/screen/selection/SelectionViewModel.java
app/src/main/java/com/framgia/fdms/utils/Constant.java
app/src/main/res/layout/fragment_request_information.xml

https://dev.framgia.com/redmine/issues/143295
Bổ sung request for, assignee, status

[BUG] Fix request edit

---

app/src/main/java/com/framgia/fdms/data/model/Request.java
app/src/main/java/com/framgia/fdms/data/source/DeviceRepository.java
app/src/main/java/com/framgia/fdms/screen/dashboard/dashboarddetail/DashBoardDetailViewModel.java
app/src/main/java/com/framgia/fdms/screen/request/requestmanager/RequestManagerViewModel.java
app/src/main/java/com/framgia/fdms/screen/request/userrequest/UserRequestViewModel.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/RequestDetailActivity.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/RequestDetailViewModel.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/information/RequestInformationFragment.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/information/RequestInformationViewModel.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/listdeviceassignment/ListDeviceAssignmentAdapter.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/listdeviceassignment/ListDeviceAssignmentContract.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/listdeviceassignment/ListDeviceAssignmentFragment.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/listdeviceassignment/ListDeviceAssignmentPresenter.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/listdeviceassignment/ListDeviceAssignmentViewModel.java
app/src/main/res/layout/item_list_device_assignment.xml

Redmine: https://dev.framgia.com/redmine/issues/142308

[BUG] Request detail fix don't show assignment

---

app/src/main/java/com/framgia/fdms/screen/devicecreation/CreateDeviceViewModel.java
app/src/main/res/layout/filter_device.xml

https://dev.framgia.com/redmine/issues/142306

[BUG] - Edit device

---

app/src/main/java/com/framgia/fdms/screen/dashboard/dashboarddetail/DashBoardDetailContract.java
app/src/main/java/com/framgia/fdms/screen/dashboard/dashboarddetail/DashBoardDetailPresenter.java
app/src/main/java/com/framgia/fdms/screen/dashboard/dashboarddetail/DashBoardDetailViewModel.java
app/src/main/java/com/framgia/fdms/screen/request/requestmanager/RequestManagerContract.java
app/src/main/java/com/framgia/fdms/screen/request/requestmanager/RequestManagerPresenter.java
app/src/main/java/com/framgia/fdms/screen/request/requestmanager/RequestManagerViewModel.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/RequestDetailActivity.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/RequestDetailContract.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/RequestDetailPagerAdapter.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/RequestDetailViewModel.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/information/OnRequestUpdateSuccessListenner.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/information/RequestInformationContract.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/information/RequestInformationFragment.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/information/RequestInformationViewModel.java
app/src/main/res/values-ja/strings.xml
app/src/main/res/values-vi/strings.xml
app/src/main/res/values/strings.xml

Redmine: https://dev.framgia.com/redmine/issues/145006

Refs task FGAS_PERSONAL DATA: Manage: My requests: "Request detail" screen display instead of "My request" screen when user edit request successfully

---

app/src/main/java/com/framgia/fdms/data/anotation/Permission.java
app/src/main/java/com/framgia/fdms/data/model/User.java
app/src/main/java/com/framgia/fdms/screen/dashboard/DashboardViewModel.java
app/src/main/java/com/framgia/fdms/screen/device/listdevice/ListDeviceViewModel.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/DeviceDetailViewModel.java
app/src/main/java/com/framgia/fdms/screen/request/userrequest/UserRequestAdapter.java
app/src/main/java/com/framgia/fdms/screen/requestcreation/RequestCreationPresenter.java
app/src/main/java/com/framgia/fdms/screen/requestcreation/RequestCreationViewModel.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/information/RequestInformationViewModel.java
app/src/main/java/com/framgia/fdms/utils/Constant.java
app/src/main/java/com/framgia/fdms/utils/binding/BindingUtils.java
app/src/main/res/layout/activity_device_detail.xml
app/src/main/res/layout/fragment_dashboard.xml
app/src/main/res/layout/fragment_request_information.xml

redmine: https://dev.framgia.com/redmine/issues/145540

Refs task 145540 - Add role Permission

---

app/src/main/java/com/framgia/fdms/screen/request/requestmanager/RequestManagerViewModel.java
app/src/main/java/com/framgia/fdms/screen/request/userrequest/UserRequestAdapter.java
app/src/main/java/com/framgia/fdms/screen/request/userrequest/UserRequestViewModel.java
app/src/main/java/com/framgia/fdms/screen/requestcreation/RequestCreationViewModel.java
app/src/main/res/layout/fragment_request_manager.xml
app/src/main/res/layout/fragment_user_request.xml
app/src/main/res/values-ja/strings.xml
app/src/main/res/values-vi/strings.xml
app/src/main/res/values/strings.xml

Redmine: https://dev.framgia.com/redmine/issues/145523

Refs task FGAS_GENERAL MANAGER - BO MANAGER: Manage: Member's request: Create a new request: New request fails to display on request list

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/framgia/fdms/data/source/DeviceDataSource.java
app/src/main/java/com/framgia/fdms/data/source/DeviceRepository.java
app/src/main/java/com/framgia/fdms/data/source/remote/DeviceRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/baseselection/BaseSelectionActivity.java
app/src/main/java/com/framgia/fdms/screen/baseselection/BaseSelectionAdapter.java
app/src/main/java/com/framgia/fdms/screen/baseselection/BaseSelectionContract.java
app/src/main/java/com/framgia/fdms/screen/baseselection/BaseSelectionPresenter.java
app/src/main/java/com/framgia/fdms/screen/baseselection/BaseSelectionViewModel.java
app/src/main/java/com/framgia/fdms/screen/devicecreation/CreateDeviceViewModel.java
app/src/main/java/com/framgia/fdms/screen/devicecreation/selectdevicestatus/SelectDeviceStatusActivity.java
app/src/main/java/com/framgia/fdms/screen/devicecreation/selectdevicestatus/SelectDeviceStatusPresenter.java
app/src/main/res/layout/activity_status_selection.xml
app/src/main/res/layout/item_status_selection.xml
app/src/main/res/values-ja/strings.xml
app/src/main/res/values-vi/strings.xml
app/src/main/res/values/strings.xml

Redmine: https://dev.framgia.com/redmine/issues/145681

Refs task FGAS_GENERAL MANAGER - BO MANAGER: Edit device can not change device status to using

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/framgia/fdms/BaseFragmentContract.java
app/src/main/java/com/framgia/fdms/data/anotation/RequestStatus.java
app/src/main/java/com/framgia/fdms/data/model/Device.java
app/src/main/java/com/framgia/fdms/data/source/AssigneeDataSource.java
app/src/main/java/com/framgia/fdms/data/source/AssigneeRepository.java
app/src/main/java/com/framgia/fdms/data/source/remote/AssigneeRemoteDataSource.java
app/src/main/java/com/framgia/fdms/data/source/remote/DeviceRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/baseselection/BaseSelectionContract.java
app/src/main/java/com/framgia/fdms/screen/baseselection/BaseSelectionViewModel.java
app/src/main/java/com/framgia/fdms/screen/device/listdevice/ListDeviceAdapter.java
app/src/main/java/com/framgia/fdms/screen/devicecreation/CreateDeviceViewModel.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/usinghistory/DeviceUsingHistoryPresenter.java
app/src/main/java/com/framgia/fdms/screen/request/requestmanager/RequestManagerContract.java
app/src/main/java/com/framgia/fdms/screen/request/requestmanager/RequestManagerPresenter.java
app/src/main/java/com/framgia/fdms/screen/request/requestmanager/RequestManagerViewModel.java
app/src/main/java/com/framgia/fdms/screen/request/requestmanager/select/assignee/SelectAssignPresenter.java
app/src/main/java/com/framgia/fdms/screen/request/requestmanager/select/assignee/SelectAssigneeActivity.java
app/src/main/java/com/framgia/fdms/screen/request/userrequest/UserRequestPresenter.java
app/src/main/java/com/framgia/fdms/screen/request/userrequest/UserRequestViewModel.java
app/src/main/res/layout/fragment_request_manager.xml
app/src/main/res/values-ja/strings.xml
app/src/main/res/values-vi/strings.xml
app/src/main/res/values/strings.xml

Redmine: https://dev.framgia.com/redmine/issues/145793

Refs - FGAS_GENERAL MANAGER- Manager:   add default filter request status, add filter by assignee

---

app/src/main/java/com/framgia/fdms/data/anotation/RequestStatus.java
app/src/main/java/com/framgia/fdms/data/source/remote/StatusRemoteDataSource.java
app/src/main/java/com/framgia/fdms/screen/dashboard/dashboarddetail/DashBoardDetailViewModel.java
app/src/main/java/com/framgia/fdms/screen/request/requestmanager/RequestManagerViewModel.java
app/src/main/java/com/framgia/fdms/screen/request/userrequest/UserRequestAdapter.java
app/src/main/java/com/framgia/fdms/screen/request/userrequest/UserRequestViewModel.java
app/src/main/java/com/framgia/fdms/screen/requestdetail/information/RequestInformationViewModel.java
app/src/main/java/com/framgia/fdms/utils/Constant.java
app/src/main/java/com/framgia/fdms/utils/binding/BindingUtils.java
app/src/main/res/layout/fragment_request_information.xml
app/src/main/res/layout/item_request_manager_adapter.xml
app/src/main/res/values-ja/strings.xml
app/src/main/res/values-vi/strings.xml
app/src/main/res/values/strings.xml

Redmine: https://dev.framgia.com/redmine/issues/145867

Refs task Refactor code

---

app/src/main/java/com/framgia/fdms/data/source/api/request/RequestCreatorRequest.java
app/src/main/java/com/framgia/fdms/screen/requestcreation/RequestCreationContract.java
app/src/main/java/com/framgia/fdms/screen/requestcreation/RequestCreationPresenter.java
app/src/main/java/com/framgia/fdms/screen/requestcreation/RequestCreationViewModel.java
app/src/main/java/com/framgia/fdms/utils/binding/BindingUtils.java
app/src/main/java/com/framgia/fdms/widget/CustomSpinner.java
app/src/main/res/layout/activity_request_creation.xml
app/src/main/res/layout/custom_spinner.xml
app/src/main/res/layout/item_group.xml
app/src/main/res/values/attrs.xml

Add group for "Create new request"

add group for create new request

---

app/src/main/res/layout/activity_request_creation.xml
app/src/main/res/values-ja/strings.xml
app/src/main/res/values-vi/strings.xml
app/src/main/res/values/strings.xml

fix create request

---

app/src/main/java/com/framgia/fdms/data/anotation/RequestStatus.java
app/src/main/java/com/framgia/fdms/screen/request/requestmanager/RequestManagerViewModel.java
app/src/main/java/com/framgia/fdms/screen/request/userrequest/UserRequestAdapter.java
app/src/main/java/com/framgia/fdms/utils/binding/BindingUtils.java
app/src/main/res/values-ja/strings.xml
app/src/main/res/values-vi/strings.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml

Redmine 
1. https://dev.framgia.com/redmine/issues/147803
2. https://dev.framgia.com/redmine/issues/147681

Refs task Change request color list request

---

app/src/main/java/com/framgia/fdms/screen/devicedetail/DeviceInfoListenner.java
app/src/main/java/com/framgia/fdms/screen/devicedetail/infomation/DeviceInfomationViewModel.java
app/src/main/java/com/framgia/fdms/screen/meetingroomdetail/DetailMeetingRoomActivity.java
app/src/main/java/com/framgia/fdms/screen/producer/ProducerViewModel.java
app/src/main/res/layout/device_information.xml
app/src/main/res/layout/fragment_device_infomation.xml
app/src/main/res/layout/fragment_user_request.xml
app/src/main/res/layout/item_device_using_history.xml
app/src/main/res/layout/item_list_device_assignment.xml
app/src/main/res/layout/item_listdevice.xml
app/src/main/res/layout/item_my_device.xml

Redmine: https://dev.framgia.com/redmine/issues/150391

Refs task #150391 update ui device focous to device code

---

app/src/main/java/com/framgia/fdms/data/source/RequestRepository.java

Redmine:  https://dev.framgia.com/redmine/issues/165059

refs code#1 fix param get member request
